apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx-image
        name: nginx-image
      ports:
      - containerPort: 80
